// <auto-generated />
using System;
using API4SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API4SQL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240102144730_InitialD")]
    partial class InitialD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API4SQL.Models.CustomerClass", b =>
                {
                    b.Property<int>("ARSMAST_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ARSMAST_NO"));

                    b.Property<float?>("AAT_AMT_1")
                        .HasColumnType("real");

                    b.Property<int>("AAT_AMT_10")
                        .HasColumnType("int");

                    b.Property<float?>("AAT_AMT_11")
                        .HasColumnType("real");

                    b.Property<int>("AAT_AMT_12")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_13")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_14")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_15")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_16")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_17")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_18")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_19")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_2")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_20")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_3")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_4")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_5")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_6")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_7")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_8")
                        .HasColumnType("int");

                    b.Property<int>("AAT_AMT_9")
                        .HasColumnType("int");

                    b.Property<string>("AAT_DESC_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("AAT_DESC_17")
                        .HasColumnType("real");

                    b.Property<float?>("AAT_DESC_18")
                        .HasColumnType("real");

                    b.Property<float?>("AAT_DESC_19")
                        .HasColumnType("real");

                    b.Property<string>("AAT_DESC_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("AAT_DESC_20")
                        .HasColumnType("real");

                    b.Property<string>("AAT_DESC_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_DESC_9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("AAT_SUP_17")
                        .HasColumnType("real");

                    b.Property<float?>("AAT_SUP_18")
                        .HasColumnType("real");

                    b.Property<float?>("AAT_SUP_19")
                        .HasColumnType("real");

                    b.Property<string>("AAT_SUP_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("AAT_SUP_20")
                        .HasColumnType("real");

                    b.Property<string>("AAT_SUP_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AAT_SUP_9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_EMAIL_ADDRESS_9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AA_PASSWORD_1")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_10")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_11")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_12")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_13")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_14")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_15")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_16")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_17")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_18")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_19")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_2")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_20")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_3")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_4")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_5")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_6")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_7")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_8")
                        .HasColumnType("float");

                    b.Property<double?>("AA_PASSWORD_9")
                        .HasColumnType("float");

                    b.Property<string>("AA_USERNAME_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AA_USERNAME_9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_ACCTG")
                        .HasColumnType("int");

                    b.Property<double?>("ARSMAST_ACCTG_HRS")
                        .HasColumnType("float");

                    b.Property<string>("ARSMAST_ADD1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_ADD2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_BACKUP")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_BALDUE")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_BARCODE")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_BDISS")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_BDISS_LDATE")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_BILLCODE")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_CATG")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_CONTACT1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_CONTACT2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_DIAL")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_DISTANCE")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_EMAIL_INVOICE")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_EZPAY_YN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_FAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_HW_5YR")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_INTERNET_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_LAST_PAY")
                        .HasColumnType("int");

                    b.Property<double?>("ARSMAST_LAT")
                        .HasColumnType("float");

                    b.Property<double?>("ARSMAST_LON")
                        .HasColumnType("float");

                    b.Property<string>("ARSMAST_MEMO1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_MEMO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_NAME1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_NOTE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_NO_EMAIL")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_NO_HW")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_NO_SW")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_PHONE1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_PHONE2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_PRINTER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_SHIP_ADD1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_SHIP_ADD2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_SM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_SS_EXPDATE")
                        .HasColumnType("int");

                    b.Property<int>("ARSMAST_SV_DATE")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_SYSTEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_TAXABLE")
                        .HasColumnType("int");

                    b.Property<double?>("ARSMAST_V_SERIALNO")
                        .HasColumnType("float");

                    b.Property<int>("ARSMAST_V_USERS")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_V_VERSION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARSMAST_WEBSITE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARSMAST_WEB_EXPDATE")
                        .HasColumnType("int");

                    b.Property<string>("ARSMAST_YR_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARSMAST_NO");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("API4SQL.Models.TicketClass", b =>
                {
                    b.Property<int>("SWORDER_NO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SWORDER_NO"));

                    b.Property<string>("SWORDER_ADDED_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_APPL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SWORDER_APP_MAINT")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_ARNO")
                        .HasColumnType("int");

                    b.Property<string>("SWORDER_ASSIGNTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SWORDER_CHARGE")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_CHARGE_HRS")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_CLASS")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_DATE")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_DATE_SENT")
                        .HasColumnType("int");

                    b.Property<string>("SWORDER_DESC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_DOC_GUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SWORDER_NO_CHG_HRS")
                        .HasColumnType("int");

                    b.Property<int>("SWORDER_PONO")
                        .HasColumnType("int");

                    b.Property<string>("SWORDER_PROG_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_REPORTED_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_SOLUTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_SOL_DATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_SOL_TIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_TIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWORDER_WHO_CLOSED")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SWORDER_NO");

                    b.ToTable("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
