using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API4SQL.Migrations
{
    /// <inheritdoc />
    public partial class InitialD : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Customer",
                columns: table => new
                {
                    ARSMAST_NO = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ARSMAST_NAME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_NAME1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_ADD1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_ADD2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_SHIP_ADD1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_SHIP_ADD2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_CONTACT1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_PHONE1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_CONTACT2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_PHONE2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_MEMO1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_MEMO2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_EMAIL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_FAX = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_SYSTEM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_CATG = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_SS_EXPDATE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_TAXABLE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BILLCODE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BALDUE = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_1 = table.Column<float>(type: "real", nullable: true),
                    AAT_DESC_2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_2 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_3 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_4 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_5 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_6 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_7 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_8 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_9 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_10 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_11 = table.Column<float>(type: "real", nullable: true),
                    AAT_DESC_12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_12 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_13 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_14 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_15 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_15 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_15 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_16 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_SUP_16 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AAT_AMT_16 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_17 = table.Column<float>(type: "real", nullable: true),
                    AAT_SUP_17 = table.Column<float>(type: "real", nullable: true),
                    AAT_AMT_17 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_18 = table.Column<float>(type: "real", nullable: true),
                    AAT_SUP_18 = table.Column<float>(type: "real", nullable: true),
                    AAT_AMT_18 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_19 = table.Column<float>(type: "real", nullable: true),
                    AAT_SUP_19 = table.Column<float>(type: "real", nullable: true),
                    AAT_AMT_19 = table.Column<int>(type: "int", nullable: false),
                    AAT_DESC_20 = table.Column<float>(type: "real", nullable: true),
                    AAT_SUP_20 = table.Column<float>(type: "real", nullable: true),
                    AAT_AMT_20 = table.Column<int>(type: "int", nullable: false),
                    AA_USERNAME_1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_1 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_2 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_3 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_4 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_5 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_6 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_7 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_8 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_9 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_10 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_11 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_12 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_13 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_14 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_15 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_15 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_15 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_16 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_16 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_16 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_17 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_17 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_17 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_18 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_18 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_18 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_19 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_19 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_19 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_USERNAME_20 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AA_PASSWORD_20 = table.Column<double>(type: "float", nullable: true),
                    AA_EMAIL_ADDRESS_20 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_NO_EMAIL = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_DIAL = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_SM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_SV_DATE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_NO_HW = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_NO_SW = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_HW_5YR = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_WEB_EXPDATE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_NOTE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_WEBSITE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_EMAIL_INVOICE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_INTERNET_EMAIL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_V_VERSION = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_V_SERIALNO = table.Column<double>(type: "float", nullable: true),
                    ARSMAST_V_USERS = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BARCODE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_PRINTER = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_LAST_PAY = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BDISS = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BDISS_LDATE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_ACCTG = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_BACKUP = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_ACCTG_HRS = table.Column<double>(type: "float", nullable: true),
                    ARSMAST_DISTANCE = table.Column<int>(type: "int", nullable: false),
                    ARSMAST_LAT = table.Column<double>(type: "float", nullable: true),
                    ARSMAST_LON = table.Column<double>(type: "float", nullable: true),
                    ARSMAST_YR_EMAIL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ARSMAST_EZPAY_YN = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customer", x => x.ARSMAST_NO);
                });

            migrationBuilder.CreateTable(
                name: "Ticket",
                columns: table => new
                {
                    SWORDER_NO = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SWORDER_DATE = table.Column<int>(type: "int", nullable: false),
                    SWORDER_TIME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_ARNO = table.Column<int>(type: "int", nullable: false),
                    SWORDER_NAME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_APPL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_REPORTED_BY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_CHARGE = table.Column<int>(type: "int", nullable: false),
                    SWORDER_PONO = table.Column<int>(type: "int", nullable: false),
                    SWORDER_DESC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_TYPE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_ASSIGNTO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_STATUS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_SOLUTION = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_SOL_DATE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_SOL_TIME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_ADDED_BY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_PROG_NAME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_DATE_SENT = table.Column<int>(type: "int", nullable: false),
                    SWORDER_WHO_CLOSED = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_CLASS = table.Column<int>(type: "int", nullable: false),
                    SWORDER_DOC_GUID = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SWORDER_CHARGE_HRS = table.Column<int>(type: "int", nullable: false),
                    SWORDER_NO_CHG_HRS = table.Column<int>(type: "int", nullable: false),
                    SWORDER_APP_MAINT = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Ticket", x => x.SWORDER_NO);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Customer");

            migrationBuilder.DropTable(
                name: "Ticket");
        }
    }
}
